'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("XAMPP_Virtual_Hosts.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to # Copyright (c) 1993-2009 Microsoft Corp.
        '''#
        '''# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
        '''#
        '''# This file contains the mappings of IP addresses to host names. Each
        '''# entry should be kept on an individual line. The IP address should
        '''# be placed in the first column followed by the corresponding host name.
        '''# The IP address and the host name should be separated by at least one
        '''# space.
        '''#
        '''# Additionally, comments (such as these) may be inserted on individual
        '''# lines or following th [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property FileHostsHeader() As String
            Get
                Return ResourceManager.GetString("FileHostsHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to # Virtual Hosts
        '''#
        '''# Required modules: mod_log_config
        '''
        '''# If you want to maintain multiple domains/hostnames on your
        '''# machine you can setup VirtualHost containers for them. Most configurations
        '''# use only name-based virtual hosts so the server doesn&apos;t need to worry about
        '''# IP addresses. This is indicated by the asterisks in the directives below.
        '''#
        '''# Please see the documentation at
        '''# &lt;URL:http://httpd.apache.org/docs/2.4/vhosts/&gt;
        '''# for further details before you try to setup virtual hosts.
        '''#
        '''# You [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property FileHttpdVHostsConfHeader() As String
            Get
                Return ResourceManager.GetString("FileHttpdVHostsConfHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;VirtualHost XAMPP_HOST:XAMPP_PORT&gt;
        '''	DocumentRoot &quot;XAMPP_DOCUMENTROOT&quot;
        '''	ServerName XAMPP_HOST
        '''
        '''	&lt;Directory &quot;XAMPP_DOCUMENTROOT&quot;&gt;
        '''		Order allow,deny
        '''		Allow from all
        '''	&lt;/Directory&gt;
        '''&lt;/VirtualHost&gt;.
        '''</summary>
        Friend ReadOnly Property httpd_vhost_conf() As String
            Get
                Return ResourceManager.GetString("httpd-vhost.conf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;VirtualHost XAMPP_HOST:XAMPP_PORT&gt;
        '''	DocumentRoot &quot;XAMPP_DOCUMENTROOT&quot;
        '''	ServerName XAMPP_HOST
        '''
        '''	SSLEngine On
        '''	SSLCertificateFile &quot;XAMPP_CERTIFICATE&quot;
        '''	SSLCertificateKeyFile &quot;XAMPP_CERTIFICATEKEY&quot;
        '''
        '''	&lt;Directory &quot;XAMPP_DOCUMENTROOT&quot;&gt;
        '''		Order allow,deny
        '''		Allow from all
        '''	&lt;/Directory&gt;
        '''&lt;/VirtualHost&gt;.
        '''</summary>
        Friend ReadOnly Property httpd_vhosts_conf__SSL_() As String
            Get
                Return ResourceManager.GetString("httpd-vhosts.conf (SSL)", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
